name: Check

on:
    pull_request:
        branches: ["main"]

jobs:
    code-check:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4.1.1
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: "1.1.x"
            - name: Install dependencies
              run: bun install
            - name: Check project files
              run: bun run check
            - name: Type-check project files
              run: bun run type-check
            - name: Build project
              run: bun run build
            #- name: Upload build files
            #  uses: actions/upload-artifact@v3
            #  with:
            #      name: build-files
            #      path: dist/

    #docker-build:
        #runs-on: ubuntu-latest
        #needs: [code-check]
        #timeout-minutes: 15
        #steps:
            #- name: Check out repo
            #  uses: actions/checkout@v4.1.1

            #- name: Set up QEMU
            #  uses: docker/setup-qemu-action@v3

            #- name: Set up Docker Buildx
            #  uses: docker/setup-buildx-action@v3

            #- name: Download build files
            #  uses: actions/download-artifact@v3
            #  with:
            #      name: build-files
            #      path: dist

            #- name: Build image
            #  uses: docker/build-push-action@v5
            #  with:
            #      context: .
            #      push: false
                  #platforms: "linux/amd64,linux/arm64,linux/arm/v7"
