name: Test Build

on:
  pull_request:
    branches: [ main ]
  push: 
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Build
      uses: docker/build-push-action@v3
      with:
        context: .
        push: false
